class ColumnViewerConfig {
  // configuration for the column based synoptic witness viewer.
  // If you change something here, it might make other changes necessary.
  // Eg. you probably would have to rewrite some of the css.

  // this is the path to the file containing the paths and metadata html snippets
  // generated by the generetate_snippets.xsl script
  snippetMetadataPath = "./witness_snippets/snippet_paths.json";

  // the id of the top level container for the witness columns
  witnessColumnsContainerId = "witness-container";
  addColumnButtonId = "column-adder";
  toggleScrollButtonId = "scroll-toggler";
  toggleEmptyLinesButtonId = "empty-line-toggler";
  toggleGlobalLineNumbersButtonId = "global-linenr-toggler";
  toggleLocalLineNumbersButtonId = "local-linenr-toggler";
  generateCitationUrlButtonId = "generate-citation-url";
  defaultNumberOfColumns = 3;
  globalScrollClass = "global-scroll-vertical";
  individualScrollClass = "individual-scroll-vertical";
  witnessLineClass = "witness-line";
  omittedLineClass = "om";
  hiddenElementClass = "hidden";
  globalLineNumberClass = "linenr-global";
  localLineNumberClass = "linenr_own";
  highlightClass = "highlight";
  neighborHighlightClass = "neigh";
  textContentClass = "text-content";
  witness_class = "witness";
  controls_container_class = "controls-container";
  removeColumnButtonClass = "remove-column-button";
  dropdown_class = "text-select";
  addColumnLabel = "Add Column";
  toggleScrollLabel = "Toggle Global Scroll";
  toggleEmptyLinesLabel = "Toggle Empty Lines";
  toggleGlobalLineNumbersLabel = "Toggle Global Line Numbers";
  toggleLocalLineNumbersLabel = "Toggle Local Line Numbers";
  generateCitationUrlLabel = "Generate Citation URL";
  controlsContainerTogglerClass = "witness_view_controls_toggle";
  controlsContainerClass = "witness_view_controls";
  removeColumnLabel = "Remove Column";
  fetchAllWitnesses = false;
}

export default ColumnViewerConfig;